
let MimeTypes
export default MimeTypes=[
  {Affix:".",ContentType:"application/x-",Comment:" "},
  {Affix:".*",ContentType:"application/octet-stream",Comment:"二进制流，不知道下载文件类型"},
  {Affix:".pdf",ContentType:"application/pdf",Comment:"PDF（Portable Document Format的简称，意为“便携式文件格式”）"},
  {Affix:".ai",ContentType:"application/postscript",Comment:"PostScript（PS）是主要用于电子产业和桌面出版领域的一种页面描述语言和编程语言。"},
  {Affix:".xml",ContentType:"application/atom+xml",Comment:"Atom feeds"},
  {Affix:".js",ContentType:"application/ecmascript",Comment:"相当于application/javascript但是严格的处理规则"},
  {Affix:".edi",ContentType:"application/EDI-X12",Comment:"EDI ANSI ASC X12数据"},
  {Affix:".edi",ContentType:"application/EDIFACT",Comment:"EDI EDIFACT数据"},
  {Affix:".json",ContentType:"application/json",Comment:"JSON（JavaScript Object Notation）"},
  {Affix:".js",ContentType:"application/javascript",Comment:"ECMAScript/JavaScript（相当于application/ecmascript但是宽松的处理规则）"},
  {Affix:".ogg",ContentType:"application/ogg",Comment:"Ogg, 视频文件格式"},
  {Affix:".rdf",ContentType:"application/rdf+xml",Comment:"资源描述框架（Resource Description Framework，缩写 RDF），是万维网联盟（W3C）提出的一组标记语言的技术标准，以便更为丰富地描述和表达网络资源的内容与结构。"},
  {Affix:".xml",ContentType:"application/rss+xml",Comment:"RSS（Really Simple Syndication,简易信息聚合）是一种消息来源格式规范，用以聚合经常发布更新数据的网站，例如博客文章、新闻、音频或视频的网摘"},
  {Affix:".xml",ContentType:"application/soap+xml",Comment:"简单对象访问协议（SOAP，全写为Simple Object Access Protocol）是交换数据的一种协议规范，使用在计算机网络Web服务（web service）中，交换带结构信息。"},
  {Affix:".woff",ContentType:"application/font-woff",Comment:"Web开放字体格式（Web Open Font Format，简称WOFF）是一种网页所采用的字体格式标准。（推荐使用；使用application/x-font-woff直到它变为官方标准）"},
  {Affix:".xhtml",ContentType:"application/xhtml+xml",Comment:"可扩展超文本标记语言（eXtensible HyperText Markup Language，XHTML），是一种标记语言，表现方式与超文本标记语言（HTML）类似，不过语法上更加严格。"},
  {Affix:".xml",ContentType:"application/xml",Comment:"可扩展标记语言（英语：eXtensible Markup Language，简称: XML），是一种标记语言。"},
  {Affix:".dtd",ContentType:"application/xml-dtd",Comment:"XML文件的文件型别定义（Document Type Definition）可以看成一个或者多个XML文件的模板，在这里可以定义XML文件中的元素、元素的属性、元素的排列方式、元素包含的内容等等。"},
  {Affix:".xml",ContentType:"application/xop+xml",Comment:"二进制优化封装协议(Xmlbinary Optimized Packaging)"},
  {Affix:".zip",ContentType:"application/zip",Comment:"ZIP压缩文件"},
  {Affix:".gzip",ContentType:"application/gzip",Comment:"Gzip是若干种文件压缩程序的简称，通常指GNU计划的实现，此处的gzip代表GNU zip。"},
  {Affix:".xls",ContentType:"application/x-xls",Comment:"XLS 就是 Microsoft Excel 工作表，是一种非常常用的电子表格格式。"},
  {Affix:".001",ContentType:"application/x-001",Comment:" "},
  {Affix:".301",ContentType:"application/x-301",Comment:" "},
  {Affix:".906",ContentType:"application/x-906",Comment:" "},
  {Affix:".a11",ContentType:"application/x-a11",Comment:" "},
  {Affix:".awf",ContentType:"application/vnd.adobe.workflow",Comment:" "},
  {Affix:".bmp",ContentType:"application/x-bmp",Comment:" "},
  {Affix:".c4t",ContentType:"application/x-c4t",Comment:" "},
  {Affix:".cal",ContentType:"application/x-cals",Comment:" "},
  {Affix:".cdf",ContentType:"application/x-netcdf",Comment:" "},
  {Affix:".cel",ContentType:"application/x-cel",Comment:" "},
  {Affix:".cg4",ContentType:"application/x-g4",Comment:" "},
  {Affix:".cit",ContentType:"application/x-cit",Comment:" "},
  {Affix:".bot",ContentType:"application/x-bot",Comment:" "},
  {Affix:".c90",ContentType:"application/x-c90",Comment:" "},
  {Affix:".cat",ContentType:"application/vnd.ms-pki.seccat",Comment:" "},
  {Affix:".cdr",ContentType:"application/x-cdr",Comment:" "},
  {Affix:".cer",ContentType:"application/x-x509-ca-cert",Comment:" "},
  {Affix:".cgm",ContentType:"application/x-cgm",Comment:" "},
  {Affix:".cmx",ContentType:"application/x-cmx",Comment:" "},
  {Affix:".crl",ContentType:"application/pkix-crl",Comment:" "},
  {Affix:".csi",ContentType:"application/x-csi",Comment:" "},
  {Affix:".cut",ContentType:"application/x-cut",Comment:" "},
  {Affix:".dbm",ContentType:"application/x-dbm",Comment:" "},
  {Affix:".cmp",ContentType:"application/x-cmp",Comment:" "},
  {Affix:".cot",ContentType:"application/x-cot",Comment:" "},
  {Affix:".crt",ContentType:"application/x-x509-ca-cert",Comment:" "},
  {Affix:".dbf",ContentType:"application/x-dbf",Comment:" "},
  {Affix:".dbx",ContentType:"application/x-dbx",Comment:" "},
  {Affix:".dcx",ContentType:"application/x-dcx",Comment:" "},
  {Affix:".dgn",ContentType:"application/x-dgn",Comment:" "},
  {Affix:".dll",ContentType:"application/x-msdownload",Comment:" "},
  {Affix:".dot",ContentType:"application/msword",Comment:" "},
  {Affix:".der",ContentType:"application/x-x509-ca-cert",Comment:" "},
  {Affix:".dib",ContentType:"application/x-dib",Comment:" "},
  {Affix:".doc",ContentType:"application/msword",Comment:" "},
  {Affix:".drw",ContentType:"application/x-drw",Comment:" "},
  {Affix:".dwf",ContentType:"application/x-dwf",Comment:" "},
  {Affix:".dxb",ContentType:"application/x-dxb",Comment:" "},
  {Affix:".edn",ContentType:"application/vnd.adobe.edn",Comment:" "},
  {Affix:".dwg",ContentType:"application/x-dwg",Comment:" "},
  {Affix:".dxf",ContentType:"application/x-dxf",Comment:" "},
  {Affix:".emf",ContentType:"application/x-emf",Comment:" "},
  {Affix:".epi",ContentType:"application/x-epi",Comment:" "},
  {Affix:".eps",ContentType:"application/postscript",Comment:" "},
  {Affix:".exe",ContentType:"application/x-msdownload",Comment:" "},
  {Affix:".fdf",ContentType:"application/vnd.fdf",Comment:" "},
  {Affix:".eps",ContentType:"application/x-ps",Comment:" "},
  {Affix:".etd",ContentType:"application/x-ebx",Comment:" "},
  {Affix:".fif",ContentType:"application/fractals",Comment:" "},
  {Affix:".frm",ContentType:"application/x-frm",Comment:" "},
  {Affix:".gbr",ContentType:"application/x-gbr",Comment:" "},
  {Affix:".g4",ContentType:"application/x-g4",Comment:" "},
  {Affix:".gl2",ContentType:"application/x-gl2",Comment:" "},
  {Affix:".hgl",ContentType:"application/x-hgl",Comment:" "},
  {Affix:".hpg",ContentType:"application/x-hpgl",Comment:" "},
  {Affix:".hqx",ContentType:"application/mac-binhex40",Comment:" "},
  {Affix:".hta",ContentType:"application/hta",Comment:" "},
  {Affix:".gp4",ContentType:"application/x-gp4",Comment:" "},
  {Affix:".hmr",ContentType:"application/x-hmr",Comment:" "},
  {Affix:".hpl",ContentType:"application/x-hpl",Comment:" "},
  {Affix:".hrf",ContentType:"application/x-hrf",Comment:" "},
  {Affix:".icb",ContentType:"application/x-icb",Comment:" "},
  {Affix:".ico",ContentType:"application/x-ico",Comment:" "},
  {Affix:".ig4",ContentType:"application/x-g4",Comment:" "},
  {Affix:".iii",ContentType:"application/x-iphone",Comment:" "},
  {Affix:".ins",ContentType:"application/x-internet-signup",Comment:" "},
  {Affix:".iff",ContentType:"application/x-iff",Comment:" "},
  {Affix:".igs",ContentType:"application/x-igs",Comment:" "},
  {Affix:".img",ContentType:"application/x-img",Comment:" "},
  {Affix:".isp",ContentType:"application/x-internet-signup",Comment:" "},
  {Affix:".jpe",ContentType:"application/x-jpe",Comment:" "},
  {Affix:".js",ContentType:"application/x-javascript",Comment:" "},
  {Affix:".jpg",ContentType:"application/x-jpg",Comment:" "},
  {Affix:".lar",ContentType:"application/x-laplayer-reg",Comment:" "},
  {Affix:".latex",ContentType:"application/x-latex",Comment:" "},
  {Affix:".lbm",ContentType:"application/x-lbm",Comment:" "},
  {Affix:".ls",ContentType:"application/x-javascript",Comment:" "},
  {Affix:".ltr",ContentType:"application/x-ltr",Comment:" "},
  {Affix:".man",ContentType:"application/x-troff-man",Comment:" "},
  {Affix:".mdb",ContentType:"application/msaccess",Comment:" "},
  {Affix:".mac",ContentType:"application/x-mac",Comment:" "},
  {Affix:".mdb",ContentType:"application/x-mdb",Comment:" "},
  {Affix:".mfp",ContentType:"application/x-shockwave-flash",Comment:" "},
  {Affix:".mi",ContentType:"application/x-mi",Comment:" "},
  {Affix:".mil",ContentType:"application/x-mil",Comment:" "},
  {Affix:".mocha",ContentType:"application/x-javascript",Comment:" "},
  {Affix:".mpd",ContentType:"application/vnd.ms-project",Comment:" "},
  {Affix:".mpp",ContentType:"application/vnd.ms-project",Comment:" "},
  {Affix:".mpt",ContentType:"application/vnd.ms-project",Comment:" "},
  {Affix:".mpw",ContentType:"application/vnd.ms-project",Comment:" "},
  {Affix:".mpx",ContentType:"application/vnd.ms-project",Comment:" "},
  {Affix:".mxp",ContentType:"application/x-mmxp",Comment:" "},
  {Affix:".nrf",ContentType:"application/x-nrf",Comment:" "},
  {Affix:".out",ContentType:"application/x-out",Comment:" "},
  {Affix:".p12",ContentType:"application/x-pkcs12",Comment:" "},
  {Affix:".p7c",ContentType:"application/pkcs7-mime",Comment:" "},
  {Affix:".p7r",ContentType:"application/x-pkcs7-certreqresp",Comment:" "},
  {Affix:".pc5",ContentType:"application/x-pc5",Comment:" "},
  {Affix:".pcl",ContentType:"application/x-pcl",Comment:" "},
  {Affix:".pdx",ContentType:"application/vnd.adobe.pdx",Comment:" "},
  {Affix:".pgl",ContentType:"application/x-pgl",Comment:" "},
  {Affix:".pko",ContentType:"application/vnd.ms-pki.pko",Comment:" "},
  {Affix:".p10",ContentType:"application/pkcs10",Comment:" "},
  {Affix:".p7b",ContentType:"application/x-pkcs7-certificates",Comment:" "},
  {Affix:".p7m",ContentType:"application/pkcs7-mime",Comment:" "},
  {Affix:".p7s",ContentType:"application/pkcs7-signature",Comment:" "},
  {Affix:".pci",ContentType:"application/x-pci",Comment:" "},
  {Affix:".pcx",ContentType:"application/x-pcx",Comment:" "},
  {Affix:".pdf",ContentType:"application/pdf",Comment:" "},
  {Affix:".pfx",ContentType:"application/x-pkcs12",Comment:" "},
  {Affix:".pic",ContentType:"application/x-pic",Comment:" "},
  {Affix:".pl",ContentType:"application/x-perl",Comment:" "},
  {Affix:".plt",ContentType:"application/x-plt",Comment:" "},
  {Affix:".png",ContentType:"application/x-png",Comment:" "},
  {Affix:".ppa",ContentType:"application/vnd.ms-powerpoint",Comment:" "},
  {Affix:".pps",ContentType:"application/vnd.ms-powerpoint",Comment:" "},
  {Affix:".ppt",ContentType:"application/x-ppt",Comment:" "},
  {Affix:".prf",ContentType:"application/pics-rules",Comment:" "},
  {Affix:".prt",ContentType:"application/x-prt",Comment:" "},
  {Affix:".ps",ContentType:"application/postscript",Comment:" "},
  {Affix:".pwz",ContentType:"application/vnd.ms-powerpoint",Comment:" "},
  {Affix:".ra",ContentType:"audio/vnd.rn-realaudio",Comment:"RealAudio是一种由RealNetworks发展的RealMedia多媒体音频文件格式，仅指RealPlayer中能够识别的音频文件，也可以理解为real格式的音频文件。"},
  {Affix:".ras",ContentType:"application/x-ras",Comment:" "},
  {Affix:".pot",ContentType:"application/vnd.ms-powerpoint",Comment:" "},
  {Affix:".ppm",ContentType:"application/x-ppm",Comment:" "},
  {Affix:".ppt",ContentType:"application/vnd.ms-powerpoint",Comment:" "},
  {Affix:".pr",ContentType:"application/x-pr",Comment:" "},
  {Affix:".prn",ContentType:"application/x-prn",Comment:" "},
  {Affix:".ps",ContentType:"application/x-ps",Comment:" "},
  {Affix:".ptn",ContentType:"application/x-ptn",Comment:" "},
  {Affix:".red",ContentType:"application/x-red",Comment:" "},
  {Affix:".rjs",ContentType:"application/vnd.rn-realsystem-rjs",Comment:" "},
  {Affix:".rlc",ContentType:"application/x-rlc",Comment:" "},
  {Affix:".rm",ContentType:"application/vnd.rn-realmedia",Comment:" "},
  {Affix:".rat",ContentType:"application/rat-file",Comment:" "},
  {Affix:".rec",ContentType:"application/vnd.rn-recording",Comment:" "},
  {Affix:".rgb",ContentType:"application/x-rgb",Comment:" "},
  {Affix:".rjt",ContentType:"application/vnd.rn-realsystem-rjt",Comment:" "},
  {Affix:".rle",ContentType:"application/x-rle",Comment:" "},
  {Affix:".rmf",ContentType:"application/vnd.adobe.rmf",Comment:" "},
  {Affix:".rmj",ContentType:"application/vnd.rn-realsystem-rmj",Comment:" "},
  {Affix:".rmp",ContentType:"application/vnd.rn-rn_music_package",Comment:" "},
  {Affix:".rmvb",ContentType:"application/vnd.rn-realmedia-vbr",Comment:" "},
  {Affix:".rnx",ContentType:"application/vnd.rn-realplayer",Comment:" "},
  {Affix:".rpm",ContentType:"audio/x-pn-realaudio-plugin",Comment:" "},
  {Affix:".rms",ContentType:"application/vnd.rn-realmedia-secure",Comment:" "},
  {Affix:".rmx",ContentType:"application/vnd.rn-realsystem-rmx",Comment:" "},
  {Affix:".rsml",ContentType:"application/vnd.rn-rsml",Comment:" "},
  {Affix:".rtf",ContentType:"application/msword",Comment:" "},
  {Affix:".rv",ContentType:"video/vnd.rn-realvideo",Comment:" "},
  {Affix:".sat",ContentType:"application/x-sat",Comment:" "},
  {Affix:".sdw",ContentType:"application/x-sdw",Comment:" "},
  {Affix:".slb",ContentType:"application/x-slb",Comment:" "},
  {Affix:".rtf",ContentType:"application/x-rtf",Comment:" "},
  {Affix:".sam",ContentType:"application/x-sam",Comment:" "},
  {Affix:".sdp",ContentType:"application/sdp",Comment:" "},
  {Affix:".sit",ContentType:"application/x-stuffit",Comment:" "},
  {Affix:".sld",ContentType:"application/x-sld",Comment:" "},
  {Affix:".smi",ContentType:"application/smil",Comment:" "},
  {Affix:".smk",ContentType:"application/x-smk",Comment:" "},
  {Affix:".smil",ContentType:"application/smil",Comment:" "},
  {Affix:".spc",ContentType:"application/x-pkcs7-certificates",Comment:" "},
  {Affix:".spl",ContentType:"application/futuresplash",Comment:" "},
  {Affix:".ssm",ContentType:"application/streamingmedia",Comment:" "},
  {Affix:".stl",ContentType:"application/vnd.ms-pki.stl",Comment:" "},
  {Affix:".sst",ContentType:"application/vnd.ms-pki.certstore",Comment:" "},
  {Affix:".tdf",ContentType:"application/x-tdf",Comment:" "},
  {Affix:".tga",ContentType:"application/x-tga",Comment:" "},
  {Affix:".sty",ContentType:"application/x-sty",Comment:" "},
  {Affix:".swf",ContentType:"application/x-shockwave-flash",Comment:" "},
  {Affix:".tg4",ContentType:"application/x-tg4",Comment:" "},
  {Affix:".tif",ContentType:"application/x-tif",Comment:" "},
  {Affix:".vdx",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".vpg",ContentType:"application/x-vpeg005",Comment:" "},
  {Affix:".vsd",ContentType:"application/x-vsd",Comment:" "},
  {Affix:".vst",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".vsw",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".vtx",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".torrent",ContentType:"application/x-bittorrent",Comment:" "},
  {Affix:".vda",ContentType:"application/x-vda",Comment:" "},
  {Affix:".vsd",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".vss",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".vst",ContentType:"application/x-vst",Comment:" "},
  {Affix:".vsx",ContentType:"application/vnd.visio",Comment:" "},
  {Affix:".wb1",ContentType:"application/x-wb1",Comment:" "},
  {Affix:".wb3",ContentType:"application/x-wb3",Comment:" "},
  {Affix:".wiz",ContentType:"application/msword",Comment:" "},
  {Affix:".wk4",ContentType:"application/x-wk4",Comment:" "},
  {Affix:".wks",ContentType:"application/x-wks",Comment:" "},
  {Affix:".wb2",ContentType:"application/x-wb2",Comment:" "},
  {Affix:".wk3",ContentType:"application/x-wk3",Comment:" "},
  {Affix:".wkq",ContentType:"application/x-wkq",Comment:" "},
  {Affix:".wmf",ContentType:"application/x-wmf",Comment:" "},
  {Affix:".wmd",ContentType:"application/x-ms-wmd",Comment:" "},
  {Affix:".wp6",ContentType:"application/x-wp6",Comment:" "},
  {Affix:".wpg",ContentType:"application/x-wpg",Comment:" "},
  {Affix:".wq1",ContentType:"application/x-wq1",Comment:" "},
  {Affix:".wri",ContentType:"application/x-wri",Comment:" "},
  {Affix:".ws",ContentType:"application/x-ws",Comment:" "},
  {Affix:".wmz",ContentType:"application/x-ms-wmz",Comment:" "},
  {Affix:".wpd",ContentType:"application/x-wpd",Comment:" "},
  {Affix:".wpl",ContentType:"application/vnd.ms-wpl",Comment:" "},
  {Affix:".wr1",ContentType:"application/x-wr1",Comment:" "},
  {Affix:".wrk",ContentType:"application/x-wrk",Comment:" "},
  {Affix:".ws2",ContentType:"application/x-ws",Comment:" "},
  {Affix:".xdp",ContentType:"application/vnd.adobe.xdp",Comment:" "},
  {Affix:".xfd",ContentType:"application/vnd.adobe.xfd",Comment:" "},
  {Affix:".xfdf",ContentType:"application/vnd.adobe.xfdf",Comment:" "},
  {Affix:".xls",ContentType:"application/vnd.ms-excel",Comment:" "},
  {Affix:".xwd",ContentType:"application/x-xwd",Comment:" "},
  {Affix:".sis",ContentType:"application/vnd.symbian.install",Comment:" "},
  {Affix:".x_t",ContentType:"application/x-x_t",Comment:" "},
  {Affix:".apk",ContentType:"application/vnd.android.package-archive",Comment:" "},
  {Affix:".x_b",ContentType:"application/x-x_b",Comment:" "},
  {Affix:".sisx",ContentType:"application/vnd.symbian.install",Comment:" "},
  {Affix:".ipa",ContentType:"application/vnd.iphone",Comment:" "},
  {Affix:".xap",ContentType:"application/x-silverlight-app",Comment:" "},
  {Affix:".xlw",ContentType:"application/x-xlw",Comment:" "},
  {Affix:".xpl",ContentType:"audio/scpls",Comment:" "},
  {Affix:".anv",ContentType:"application/x-anv",Comment:" "},
  {Affix:".uin",ContentType:"application/x-icq",Comment:" "},

  {Affix:".323",ContentType:"text/h323",Comment:" "},
  {Affix:".biz",ContentType:"text/xml",Comment:" "},
  {Affix:".cml",ContentType:"text/xml",Comment:" "},
  {Affix:".asa",ContentType:"text/asa",Comment:" "},
  {Affix:".asp",ContentType:"text/asp",Comment:" "},
  {Affix:".css",ContentType:"text/css",Comment:"层叠样式表（英语：Cascading Style Sheets，简写CSS），又称串样式列表、层次结构式样式表文件，一种用来为结构化文档（如HTML文档或XML应用）添加样式（字体、间距和颜色等）的计算机语言，由W3C定义和维护。"},
  {Affix:".csv",ContentType:"text/csv",Comment:"逗号分隔值（Comma-Separated Values，CSV，有时也称为字符分隔值，因为分隔字符也可以不是逗号），其文件以纯文本形式存储表格数据（数字和文本）。"},
  {Affix:".dcd",ContentType:"text/xml",Comment:" "},
  {Affix:".dtd",ContentType:"text/xml",Comment:" "},
  {Affix:".ent",ContentType:"text/xml",Comment:" "},
  {Affix:".fo",ContentType:"text/xml",Comment:" "},
  {Affix:".htc",ContentType:"text/x-component",Comment:" "},
  {Affix:".html",ContentType:"text/html",Comment:" "},
  {Affix:".htx",ContentType:"text/html",Comment:" "},
  {Affix:".htm",ContentType:"text/html",Comment:" "},
  {Affix:".htt",ContentType:"text/webviewhtml",Comment:" "},
  {Affix:".jsp",ContentType:"text/html",Comment:" "},
  {Affix:".math",ContentType:"text/xml",Comment:" "},
  {Affix:".mml",ContentType:"text/xml",Comment:" "},
  {Affix:".mtx",ContentType:"text/xml",Comment:" "},
  {Affix:".plg",ContentType:"text/html",Comment:" "},
  {Affix:".rdf",ContentType:"text/xml",Comment:" "},
  {Affix:".rt",ContentType:"text/vnd.rn-realtext",Comment:" "},
  {Affix:".sol",ContentType:"text/plain",Comment:" "},
  {Affix:".spp",ContentType:"text/xml",Comment:" "},
  {Affix:".stm",ContentType:"text/html",Comment:" "},
  {Affix:".svg",ContentType:"text/xml",Comment:" "},
  {Affix:".tld",ContentType:"text/xml",Comment:" "},
  {Affix:".txt",ContentType:"text/plain",Comment:"纯文字内容"},
  {Affix:".uls",ContentType:"text/iuls",Comment:" "},
  {Affix:".vml",ContentType:"text/xml",Comment:" "},
  {Affix:".tsd",ContentType:"text/xml",Comment:" "},
  {Affix:".vcf",ContentType:"text/x-vcard",Comment:" "},
  {Affix:".vxml",ContentType:"text/xml",Comment:" "},
  {Affix:".wml",ContentType:"text/vnd.wap.wml",Comment:" "},
  {Affix:".wsdl",ContentType:"text/xml",Comment:" "},
  {Affix:".wsc",ContentType:"text/scriptlet",Comment:" "},
  {Affix:".xdr",ContentType:"text/xml",Comment:" "},
  {Affix:".xql",ContentType:"text/xml",Comment:" "},
  {Affix:".xsd",ContentType:"text/xml",Comment:" "},
  {Affix:".xslt",ContentType:"text/xml",Comment:" "},
  {Affix:".xml",ContentType:"text/xml",Comment:" "},
  {Affix:".xq",ContentType:"text/xml",Comment:" "},
  {Affix:".xquery",ContentType:"text/xml",Comment:" "},
  {Affix:".xsl",ContentType:"text/xml",Comment:" "},
  {Affix:".xhtml",ContentType:"text/html",Comment:" "},
  {Affix:".odc",ContentType:"text/x-ms-odc",Comment:" "},
  {Affix:".r3t",ContentType:"text/vnd.rn-realtext3d",Comment:" "},
  {Affix:".sor",ContentType:"text/plain",Comment:" "},

  {Affix:".acp",ContentType:"audio/x-mei-aac",Comment:" "},
  {Affix:".aif",ContentType:"audio/aiff",Comment:" "},
  {Affix:".aiff",ContentType:"audio/aiff",Comment:" "},
  {Affix:".aifc",ContentType:"audio/aiff",Comment:" "},
  {Affix:".au",ContentType:"audio/basic",Comment:" "},
  {Affix:".la1",ContentType:"audio/x-liquid-file",Comment:" "},
  {Affix:".lavs",ContentType:"audio/x-liquid-secure",Comment:" "},
  {Affix:".lmsff",ContentType:"audio/x-la-lms",Comment:" "},
  {Affix:".m3u",ContentType:"audio/mpegurl",Comment:" "},
  {Affix:".midi",ContentType:"audio/mid",Comment:" "},
  {Affix:".mid",ContentType:"audio/mid",Comment:" "},
  {Affix:".mp2",ContentType:"audio/mp2",Comment:" "},
  {Affix:".mp3",ContentType:"audio/mp3",Comment:" "},
  {Affix:".mp4",ContentType:"audio/mp4",Comment:"MP4，全称MPEG-4 Part 14，是一种使用MPEG-4的多媒体计算机文件格式，扩展名为.mp4，以存储数字音频及数字视频为主。"},
  {Affix:".mnd",ContentType:"audio/x-musicnet-download",Comment:" "},
  {Affix:".mp1",ContentType:"audio/mp1",Comment:" "},
  {Affix:".mns",ContentType:"audio/x-musicnet-stream",Comment:" "},
  {Affix:".mpga",ContentType:"audio/rn-mpeg",Comment:" "},
  {Affix:".pls",ContentType:"audio/scpls",Comment:" "},
  {Affix:".ram",ContentType:"audio/x-pn-realaudio",Comment:" "},
  {Affix:".rmi",ContentType:"audio/mid",Comment:" "},
  {Affix:".rmm",ContentType:"audio/x-pn-realaudio",Comment:" "},
  {Affix:".snd",ContentType:"audio/basic",Comment:" "},
  {Affix:".wav",ContentType:"audio/wav",Comment:" "},
  {Affix:".wax",ContentType:"audio/x-ms-wax",Comment:" "},
  {Affix:".wma",ContentType:"audio/x-ms-wma",Comment:" "},

  {Affix:".asf",ContentType:"video/x-ms-asf",Comment:" "},
  {Affix:".asx",ContentType:"video/x-ms-asf",Comment:" "},
  {Affix:".avi",ContentType:"video/avi",Comment:" "},
  {Affix:".IVF",ContentType:"video/x-ivf",Comment:" "},
  {Affix:".m1v",ContentType:"video/x-mpeg",Comment:" "},
  {Affix:".m2v",ContentType:"video/x-mpeg",Comment:" "},
  {Affix:".m4e",ContentType:"video/mpeg4",Comment:" "},
  {Affix:".movie",ContentType:"video/x-sgi-movie",Comment:" "},
  {Affix:".mp2v",ContentType:"video/mpeg",Comment:" "},
  {Affix:".mp4",ContentType:"video/mpeg4",Comment:"MP4，全称MPEG-4 Part 14，是一种使用MPEG-4的多媒体计算机文件格式，扩展名为.mp4，以存储数字音频及数字视频为主。"},
  {Affix:".mpa",ContentType:"video/x-mpg",Comment:" "},
  {Affix:".mpe",ContentType:"video/x-mpeg",Comment:" "},
  {Affix:".mpg",ContentType:"video/mpg",Comment:" "},
  {Affix:".mpeg",ContentType:"video/mpg",Comment:" "},
  {Affix:".mps",ContentType:"video/x-mpeg",Comment:" "},
  {Affix:".mpv",ContentType:"video/mpg",Comment:" "},
  {Affix:".mpv2",ContentType:"video/mpeg",Comment:" "},
  {Affix:".wm",ContentType:"video/x-ms-wm",Comment:" "},
  {Affix:".wmv",ContentType:"video/x-ms-wmv",Comment:" "},
  {Affix:".wmx",ContentType:"video/x-ms-wmx",Comment:" "},
  {Affix:".wvx",ContentType:"video/x-ms-wvx",Comment:" "},

  {Affix:".tif",ContentType:"image/tiff",Comment:"标签图像文件格式（Tagged Image File Format，简写为TIFF）是一种主要用来存储包括照片和艺术图在内的图像的文件格式。它最初由Aldus公司与微软公司一起为PostScript打印开发。"},
  {Affix:".fax",ContentType:"image/fax",Comment:" "},
  {Affix:".gif",ContentType:"image/gif",Comment:"图像互换格式（GIF，Graphics Interchange Format）是一种位图图形文件格式，以8位色（即256种颜色）重现真彩色的图像。"},
  {Affix:".ico",ContentType:"image/x-icon",Comment:" "},
  {Affix:".jfif",ContentType:"image/jpeg",Comment:" "},
  {Affix:".jpe",ContentType:"image/jpeg",Comment:" "},
  {Affix:".jpeg",ContentType:"image/jpeg",Comment:"JPEG是一种针对相片图像而广泛使用的一种有损压缩标准方法。"},
  {Affix:".jpg",ContentType:"image/jpeg",Comment:" "},
  {Affix:".net",ContentType:"image/pnetvue",Comment:" "},
  {Affix:".png",ContentType:"image/png",Comment:"便携式网络图形（Portable Network Graphics，PNG）是一种无损压缩的位图图形格式，支持索引、灰度、RGB三种颜色方案以及Alpha通道等特性。"},
  {Affix:".rp",ContentType:"image/vnd.rn-realpix",Comment:" "},
  {Affix:".tif",ContentType:"image/tiff",Comment:" "},
  {Affix:".tiff",ContentType:"image/tiff",Comment:" "},
  {Affix:".wbmp",ContentType:"image/vnd.wap.wbmp",Comment:" "},


{Affix:".eml",ContentType:"message/rfc822",Comment:" "},
  {Affix:".mht",ContentType:"message/rfc822",Comment:" "},
  {Affix:".mhtml",ContentType:"message/rfc822",Comment:" "},
  {Affix:".nws",ContentType:"message/rfc822",Comment:" "},

{Affix:".907",ContentType:"drawing/907",Comment:" "},
  {Affix:".slk",ContentType:"drawing/x-slk",Comment:" "},
  {Affix:".top",ContentType:"drawing/x-top",Comment:" "},

{Affix:".class",ContentType:"java/*",Comment:" "},
  {Affix:".java",ContentType:"java/*",Comment:" "},

]
/**
 * 根据类型判断是媒体类型的简称.
 * 如image/tiff 显示 为 "image"
 * @param contentType
 */
export function whichTypeAs(contentType) {
    if(contentType.indexOf("text/css")>-1){
      return "css"
    }
    if(contentType.indexOf("text/plain")>-1){
      return "text"
    }
    if(contentType.indexOf("text/html")>-1){
      return "html"
    }
    if(contentType.indexOf("application/xml")>-1){
      return "xml"
    }
    if(contentType.indexOf("application/json")>-1){
      return "json";
    }
    if(contentType.indexOf("image/")>-1){
      return "image"
    }
    if(contentType.indexOf("application/javascript")>-1){
      return "js"
    }
    if(contentType.indexOf("application/octet-stream")>-1){
      return "file"
    }

}
export function TypesList() {
  return ["json","image","js","vidio","audio","html","file","xml","text"]

}
export function TypesNameList() {
  return [
    {text:"json",value:"json"},
    {text:"image",value:"image"},
    {text:"js",value:"js"},
    {text:"vidio",value:"vidio"},
    {text:"audio",value:"audio"},
    {text:"html",value:"html"},
    {text:"file",value:"file"},
    {text:"xml",value:"xml"},
    {text:"text",value:"text"}
  ]
}
